twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
        varGlobals: '@App\Service\TwigGlobalService'
  
   

when@test:
    twig:
        strict_variables: true
