home_admin:
    path: "/adminsicad/{_locale}"
    controller: App\Controller\HomeAdminController::index
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%' 
    
update_profile:
    path: "/adminsicad/update-profile/{_locale}"
    controller: App\Controller\UserController::updateProfile
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%'

update_password:
    path: "/adminsicad/update-password/{_locale}"
    controller: App\Controller\UserController::updatePassword
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%'
   
   
    
 
  
   