add_article:
    path: "/adminsicad/add-article/{_locale}"
    controller: App\Controller\ArticleController::addArticle
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%' 

update_article:
    path: "/adminsicad/update-article/{slug}/{_locale}"
    controller: App\Controller\ArticleController::updateArticle
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%' 


list_article:
    path: "/adminsicad/list-article/{_locale}"
    controller: App\Controller\ArticleController::listArticle
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%' 


delete_article:
    path: "/adminsicad/delete-article/{slug}/{_locale}"
    controller: App\Controller\ArticleController::deleteArticle
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%'  


validate_article:
    path: "/adminsicad/validate-article/{slug}/{_locale}"
    controller: App\Controller\ArticleController::validateArticle
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%'   


publish_article:
    path: "/adminsicad/publish-article/{slug}/{_locale}"
    controller: App\Controller\ArticleController::publishArticle
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%'                           
