login:
    path: "/login"
    controller: App\Controller\SecurityController::login
    #methods: POST

logout:
    path: "/logout"
    controller: App\Controller\SecurityController::logout
    #methods: POST    



registration:
    path: "/register"
    controller: App\Controller\SecurityController::register
    #methods: POST