registration:
    path: "/register/{_locale}"
    controller: App\Controller\SecurityController::register
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%'

login:
    path: "/login/{_locale}"
    controller: App\Controller\SecurityController::login
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%'
    
logout:
    path: "/logout"
    controller: App\Controller\SecurityController::logout
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%'   

